# Generated by Django 3.0.3 on 2020-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
            ],
        ),
    ]
